auto:	          true

root: /
permalink: /:title/
markdown: rdiscount
pygments: true
paginate: 5

title: Ramiel's blog
feed:             /atom.xml
author:
    name:         Ramiel
    weibo:      http://weibo.com/runninghack
description:      "Ramiel\'s Blog"
author_info:      <a href="https://runninghack.github.com/about">Ramiel</a>
email: "zl.ramiel@gmail.com"

copyright:
    - &copy; 2013
